apiVersion: v1
kind: Service
metadata:
  name: mi-aplicacion-service
spec:
  selector:
    app: welcome-to-docker 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer